version: "3.7"
name: bookflow
services:
  maria_db:
    image: mariadb:11.0.2
    container_name: bookflow-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bookflow-mariadb
      MYSQL_USER: bookflow-admin
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - project-database-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bookflow-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: bookflow-mariadb
      MYSQL_ROOT_PASSWORD: passwd

#  swagger_ui:
#    image: swaggerapi/swagger-ui:v5.0.0-alpha.15
#    container_name: swagger_container
#    environment:
#      API_URL: http://localhost:8080/openapi
#    ports:
#      - "8080:8080"
#    volumes:
#      - project-database-data:/data

volumes:
  project-database-data: